# Generated by Django 5.2.13 on 2026-04-18 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamscape_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
