# Generated by Django 5.2.13 on 2026-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamscape_app', '0002_wish_created_at_wish_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/wish_images'),
        ),
    ]
