# Generated by Django 5.2.13 on 2026-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamscape_app', '0003_alter_wish_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='status',
            field=models.CharField(choices=[('dreaming', 'Мечтаю'), ('in_process', 'В процессе'), ('done', 'Выполнено')], default='Мечтаю', max_length=20),
        ),
        migrations.AddField(
            model_name='wish',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('link', 'Link only'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
